from __future__ import annotations

from pathlib import Path
from typing import Literal


def build_prepare_prompt(
    *,
    repo_path: Path,
    synthesis_path: Path,
    knowledge_path: Path,
    batch_dir: Path,
    workspace_plan_path: Path | None,
    skills_workdir: Path,
    skills_dir: str,
    state_path: Path,
    base_revision: str,
    skill_root: Path,
    knowledge_root: Path,
    workflow: Literal["loop", "simulate"] = "loop",
) -> str:
    iteration_contract = skill_root / "references" / "iteration-contract.md"
    skill_update_contract = skill_root / "references" / "skill-update-contract.md"
    workspace_scaffold_contract = skill_root / "references" / "workspace-scaffold-contract.md"
    scripts_dir = skill_root / "scripts"
    knowledge_exists = knowledge_path.is_file()
    plan_exists = workspace_plan_path is not None and workspace_plan_path.is_file()
    default_plan_path = batch_dir / "workspace-plan.json"

    if plan_exists and workspace_plan_path is not None:
        plan_step = f"""4. **Workspace plan (already generated by CLI):** read `{workspace_plan_path.as_posix()}`.
   - One entry in `workspaces[]` → one directory `{batch_dir.as_posix()}/<workspace>/` with operator `<workspace>.py`.
   - Use `knowledge_lessons`, `launch_functions`, and `kernels_in_operator` from each entry when writing `validation-meta.json`.
   - If warnings in the plan need manual fixes, update the plan JSON before scaffolding.
   - Re-run planning only if the plan is missing or stale:

     triton-agent pattern-validation-plan -i {repo_path.as_posix()} \\
       --knowledge {knowledge_path.relative_to(repo_path).as_posix() if knowledge_path.is_relative_to(repo_path) else knowledge_path.as_posix()} \\
       --batch-dir {batch_dir.name} \\
       --base {base_revision} \\
       [--skip-launch <host_launch_fn> ...]"""
    elif knowledge_exists:
        plan_step = f"""4. **Generate workspace plan** from the knowledge base (required):

     triton-agent pattern-validation-plan -i {repo_path.as_posix()} \\
       --knowledge {knowledge_path.relative_to(repo_path).as_posix() if _is_relative(knowledge_path, repo_path) else knowledge_path.as_posix()} \\
       --batch-dir {batch_dir.name} \\
       --base {base_revision} \\
       [--skip-launch <host_launch_fn> ...]

   Then read `{default_plan_path.as_posix()}` and scaffold one workspace per `workspaces[]` entry."""
    else:
        plan_step = f"""4. No `{knowledge_path.name}` found — plan workspaces manually from `{synthesis_path.name}` and
   `{workspace_scaffold_contract.as_posix()}` (one launch function per workspace when possible)."""

    if workflow == "simulate":
        init_step = (
            f"1. Simulate loop state is managed by the CLI at `{state_path.as_posix()}`. "
            "Do not run `init_loop_state.py`."
        )
        record_step = f"""7. Record scaffold completion in simulate state:

   python3 {scripts_dir.as_posix()}/record_simulate_iteration.py \\
     --state {state_path.as_posix()} --phase prepare \\
     --note "workspaces ready for simulate agents\""""
    else:
        init_step = f"""1. Initialize loop state if `{state_path.as_posix()}` does not exist:

   python3 {scripts_dir.as_posix()}/init_loop_state.py \\
     --repo {repo_path.as_posix()} \\
     --synthesis {synthesis_path.name} \\
     --batch-dir {batch_dir.name} \\
     --skills-dir {skills_dir} \\
     --base {base_revision}"""
        record_step = f"""7. Record scaffold completion:

   python3 {scripts_dir.as_posix()}/record_iteration.py \\
     --state {state_path.as_posix()} --phase scaffold \\
     --note "workspaces ready for CLI optimize\""""

    flow_label = (
        "pattern-validation-simulate (dry-run planning loop)"
        if workflow == "simulate"
        else "the CLI-driven loop"
    )

    return f"""\
Prepare pattern-validation workspaces for {flow_label}. **Do not** run `optimize-batch` or nested optimize agents.

The user provides markdown reports in the repo; you scaffold batch workspaces from them.

Read before acting:

  {iteration_contract.as_posix()}
  {skill_update_contract.as_posix()}
  {skill_root.as_posix()}/references/knowledge-base-scaffold-contract.md
  {workspace_scaffold_contract.as_posix()}
  {skill_root.as_posix()}/SKILL.md

Repository root:

  {repo_path.as_posix()}

Synthesis report:

  {synthesis_path.as_posix()}

Knowledge base:

  {knowledge_path.as_posix()} {"(present)" if knowledge_exists else "(missing — fall back to synthesis)"}

Batch root (create workspaces here):

  {batch_dir.as_posix()}

Persistent loop skills workdir (edit knowledge here only):

  {skills_workdir.as_posix()}

Loop state file:

  {state_path.as_posix()}

Git base revision for pre-optimization snapshots:

  {base_revision}

Required steps:

{init_step}

2. Read `{synthesis_path.name}` and `{knowledge_path.name}` when present. Update pattern cards under `{knowledge_root.as_posix()}/references/patterns/` only.
3. Regenerate `{knowledge_root.as_posix()}/references/pattern_index.md`.
{plan_step}
5. Scaffold workspaces under `{batch_dir.as_posix()}`: **workspace-named** directories and operator files per the plan; helper `.py` only under `deps/`.
   - Operator file = **minimal extract** for this workspace's `launch_functions` / `kernels_in_operator` only — do not copy the whole `source_path` file when the plan splits by launch.
   - `deps/` fallback copies whole repo modules for imports; do not trim `deps/` — trim the operator instead.
   - `dependency_dir` must be the literal string `deps` (never `{{deps}}` or other placeholders).
   - Copy repo `test_*.py` as **reference** files named `test_*.py.txt` (not runnable pytest). Record them in `validation-meta.json` → `copied_tests`.
   - The optimize CLI will tell the agent these `.py.txt` files document dtype and shapes only.
   - After scaffolding, the CLI runs `sync_workspace_dependencies.py` to inject repo `sys.path` at the top of each operator (keep original `from fla...` imports), run import smoke, and only copy into `deps/fla/` when smoke fails or you pass `--copy-deps`:
     python3 {scripts_dir.as_posix()}/sync_workspace_dependencies.py --batch-root {batch_dir.as_posix()} --repo {repo_path.as_posix()}
6. Run scaffold verification from repo root:

   triton-agent pattern-validation-verify -i {batch_dir.as_posix()}

   Fix every issue until it exits 0.
{record_step}

Rules:

- Do not run `triton-agent optimize-batch` (the CLI runs optimize after you finish).
- Do not edit staged backend install skills for knowledge updates.
- Do not copy entire multi-kernel `source_path` files when the plan lists multiple kernels.
"""


def _is_relative(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def build_analyze_prompt(
    *,
    repo_path: Path,
    batch_dir: Path,
    skills_workdir: Path,
    state_path: Path,
    audit_report_path: Path,
    iteration: int,
    max_iterations: int,
    skill_root: Path,
    knowledge_root: Path,
) -> str:
    iteration_contract = skill_root / "references" / "iteration-contract.md"
    scripts_dir = skill_root / "scripts"

    return f"""\
Analyze pattern-validation optimize evidence and decide whether the loop can complete.

Read:

  {iteration_contract.as_posix()}
  {skill_root.as_posix()}/SKILL.md
  {audit_report_path.as_posix()}

Repository root:

  {repo_path.as_posix()}

Batch root:

  {batch_dir.as_posix()}

Skills workdir:

  {skills_workdir.as_posix()}

Loop state:

  {state_path.as_posix()}

Current iteration: {iteration} / {max_iterations}

The evidence report aggregates `opt-round-*/attempts.md`, `summary.md`, and related artifacts.
`heuristic_suggested_pass` is a **hint only** (substring match on pattern IDs). You must judge whether optimize rounds actually applied synthesis-backed mechanisms.

Some workspaces may have failed optimize-batch runs; still review their partial `opt-round-*`
artifacts and `validation-meta.json` before deciding next steps.

Required steps:

1. Read `{audit_report_path.as_posix()}` and open round artifacts when excerpts are insufficient.
2. For each active workspace, decide pass/fail against synthesis and `validation-meta.json` `expected_patterns`.
3. If skills need fixes, edit `{knowledge_root.as_posix()}/references/patterns/`, regenerate `pattern_index.md`, and record a skill-update note.
4. When you are confident a workspace passed, archive it:

   python3 {scripts_dir.as_posix()}/audit_batch.py \\
     --batch-root {batch_dir.as_posix()} \\
     --archive-passed

   Use `--archive-passed` only for workspaces you reviewed; do not rely on heuristics alone.
5. If **all** validation targets are satisfied (`active_remaining` empty in a fresh evidence report), write `{batch_dir.as_posix()}/VALIDATION_SUMMARY.md` and:

   python3 {scripts_dir.as_posix()}/record_iteration.py \\
     --state {state_path.as_posix()} --phase complete \\
     --audit-report {audit_report_path.as_posix()} \\
     --note "pattern validation complete"

6. If more skill/optimize iterations are needed and iteration < {max_iterations}, record analysis without marking complete:

   python3 {scripts_dir.as_posix()}/record_iteration.py \\
     --state {state_path.as_posix()} --phase audit \\
     --audit-report {audit_report_path.as_posix()} \\
     --increment-iteration \\
     --note "needs another optimize iteration"

Rules:

- Do not run `triton-agent optimize-batch` (the CLI runs optimize between prepare/analyze phases).
- Do not hand-edit `pattern_index.md`.
- Do not delete `baseline/` when iterating skills.
"""
